version: '3.8'

services:    
  social:
    build: .
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - PG_HOST=${PG_HOST}
      - PG_PORT=${PG_PORT}
    depends_on:
      - social-db
    volumes:
      - go-modules:/go/pkg/mod
    restart: unless-stopped
    networks:
      - app-network

  social-db:
    image: postgres:15
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${PG_NAME}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASS}
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - social-db_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER} -d ${PG_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
  nats:
    image: nats:latest
    restart: unless-stopped
    command: ["-js"]
    volumes:
      - nats_data:/data
    environment:
      - NATS_SERVER_NAME=cosmo-nats
    networks:
      - app-network

volumes:
  social-db_data:
  nats_data:
  go-modules:

networks:
  app-network:
    driver: bridge